# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20190603_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('disount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='restapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='restapp.SaleInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleinvoicedetail',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='restapp.Medicine'),
        ),
        migrations.AddField(
            model_name='saleinvoicedetail',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_rate', to='restapp.Medicine'),
        ),
    ]
