# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-14 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20190614_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoicedetail',
            name='rate',
        ),
    ]
