# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='municipality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='p_m', to='testapp.District'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_d', to='testapp.District'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_p', to='testapp.Province'),
        ),
    ]
