# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190521_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_m', to='testapp.Municipality'),
        ),
    ]
